### ISSUE TITLE
Merging Fails If Turnitin Activity is not Found

### ISSUE THREAD

**Issue by nbozhkov-ucl** [ndunand/moodle-tool_mergeusers#216]
Merging is failing if for some reason turnitin activity that it needs is not found. Any ideas how this can be resolved?

Moodle 3.11.10
turnitintooltwo  $plugin->version   = 2022051201;

Error from the merge below: 

> Exception thrown when merging: 'Can not find turnitintooltwo activity with id 3995".
> 
> Trace:
> #0 /var/www/site/admin/tool/mergeusers/lib/mergeusertool.php(271): MergeUserTool->updateGrades('682639', '802738')
> #1 /var/www/site/admin/tool/mergeusers/lib/mergeusertool.php(192): MergeUserTool->_merge('682639', '802738')
> #2 /var/www/site/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('682639', '802738')
> #3 {main}

**Comment by nbozhkov-ucl** [comment]
The error was due to bad data in the moodle database. Closing this issue.
