### ISSUE TITLE
Merging Fails if Attendance Activity is not Found

### ISSUE THREAD

**Issue by nbozhkov-ucl** [ndunand/moodle-tool_mergeusers#217]
Merging is failing if for some reason attendance activity that it needs is not found. Any ideas how this can be resolved?

Moodle 3.11.10
https://github.com/danmarsden/moodle-mod_attendance/ - $plugin->version  = 2021082609;

Error from the merge below:

> Exception thrown when merging: 'Can not find attendance activity with id 10401".
> 
> Trace:
> #0 /var/www/site/admin/tool/mergeusers/lib/mergeusertool.php(271): MergeUserTool->updateGrades('704703', '825846')
> #1 /var/www/site/admin/tool/mergeusers/lib/mergeusertool.php(192): MergeUserTool->_merge('704703', '825846')
> #2 /var/www/site/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('704703', '825846')

**Comment by nbozhkov-ucl** [comment]
The error was due to bad data in the moodle database. Closing this issue.
