### ISSUE TITLE
Activities (assignment + database): Submission & Grade

### ISSUE THREAD

**Issue by romancuk** [ndunand/moodle-tool_mergeusers#93]
When merging two users that have submited file or that they were already graded, two types of errors can appeare:

Duplicate entry '3324-77998-0-0' for key 'mdl_assisubm_assusegroatt_uix'
Duplicate entry '2577-38299-0' for key 'mdl_assigrad_assuseatt_uix'

I'm not expert in Moodle nor have knowledge to see into the database, but I have done some researche work. If I make some mistakes here, please correct me.

Submition:
At assignment it is possible to allow submiittion of only one or many files. If only one is allowed - that is the problem. And if two or more is allowed - there should be no problem - but there is.   If user submitted two files (with the same name or two different names) with both user-accounts (one file per account), than there is "submission error".  Then user delete one submitted file, and problem is stil there. The same thing holds for database activity.    By my opinion, if submition is deleted, some records still remains in database.

Possible solutions:
- If file was deleted - ignore that record  
- if two files have the same name - ignore one

- if two files have different names - ignore file which is older   or    which has higher grade   or   which has no grade.     Better solution is that new ".zip" file is created and both files is archived there.
if user submited only text - append one text to another.

Grading:
If two users got grade at the seam activity - there is problem.  Even if on grade is deleted by teacher or manager, there is the same problem. Even if submittion was removed by user, problem remains.

Possible solutions:
- if grade is already deleted - ignore it
- if grades are the same - ignore one

- ignore lower grade.  But plugin can't know the meaning of lower and greater.
- ignore older grade.   ???
- combine both grades.   ???
Probably the most buletprof solution will be, that plugun outputs exact place where error accured (class name (id), assignment name (id) and grade for both users) and that manager deletes one. After that, deleted grade should be ignored.

**Comment by heather-williams** [comment]
I am also seeing this issue when trying to merge two users that are enrolled in the same class:

{code}
Exception thrown when merging: 'Error writing to database". 
Duplicate entry '10437-49347-0-0' for key 'mdl_assisubm_assusegroatt_uix' 
Trace: 
#0 /opt/rlcache/www/moodle_prod/lib/dml/mysqli_native_moodle_database.php(974): moodle_database->query_end(false) 
#1 /opt/rlcache/www/moodle_prod/admin/tool/mergeusers/lib/table/generictablemerger.php(225): mysqli_native_moodle_database->execute('UPDATE mdl_assi...') 
#2 /opt/rlcache/www/moodle_prod/admin/tool/mergeusers/lib/table/generictablemerger.php(80): GenericTableMerger->updateRecords(Array, Array, 'userid', Array, Array) 
#3 /opt/rlcache/www/moodle_prod/admin/tool/mergeusers/lib/mergeusertool.php(281): GenericTableMerger->merge(Array, Array, Array) 
#4 /opt/rlcache/www/moodle_prod/admin/tool/mergeusers/lib/mergeusertool.php(216): MergeUserTool->_merge('49347', '45878') 
#5 /opt/rlcache/www/moodle_prod/admin/tool/mergeusers/index.php(135): MergeUserTool->merge('49347', '45878') 
#6 {main}
{code}

**Comment by jpahullo** [comment]
Hi all!

This index is already treated in our last version of the plugin. Check `config/config.php` and go to the key `compoundindexes`: there you should see some lines like these:

```
       'assign_submission' => array( // unique key mdl_assisubm_assusegroatt_uix
            'userfield' => array('userid'),
            'otherfields' => array('assignment', 'groupid', 'attemptnumber'),
        ),
```

Therefore, are you using the last version of this plugin?

Thank you so much for your time and reporting back issues.

Jordi

**Comment by jpahullo** [comment]
Hi all!

However, the issue stated by @romancuk still remains.

I think that we can take benefit from Moodle by using events to proceed correspondingly when a grade/submission is deleted, to let Moodle do what is expected to do on those events.

Thinking about it. What do you think?

Jordi

**Comment by jpahullo** [comment]
Thanks for raising this issue @romancuk and @heather-williams ,

This was about a very old Moodle version, and plugin evolved since then.

Closing. If something related still happens, open a new issue, please.

Jordi
